describe("对相关动作的测试", () => {
  it("测试问题的点赞/踩/收藏/删除", () => {
    cy.visit('http://localhost:3000/login')
    cy.get("[placeholder=\"用户名\"]").type("user1")
    cy.get("[placeholder=\"密码\"]").type("1")
    cy.get("[data-testid=\"login-button\"]").click()
    cy.url().should("eq", "http://localhost:3000/?page=0")
    cy.contains("去提问！").click()
    cy.get("[placeholder=\"问题标题\"]").should("be.visible")
    cy.get("[placeholder=\"问题标题\"]").type("如何评价软件工程这个专业")
    cy.get("[placeholder=\"问题内容\"]").type("rt，如何评价软件工程，就业前景如何，学习难度如何")
    cy.contains("校园生活").click()
    cy.contains("OK").click()
    cy.url().should("include", "/ques")
    cy.contains("校园生活").should("be.visible")
    cy.wait(1000)
    cy.get("[data-testId=\"like-question-button\"]").click()
    cy.get("[data-testId=\"like-question-count\"]").should("have.text", "1")
    cy.get("[data-testId=\"like-question-button\"]").click()
    cy.get("[data-testId=\"like-question-count\"]").should("have.text", "0")
    cy.get("[data-testId=\"dislike-question-button\"]").click()
    cy.get("[data-testId=\"dislike-question-count\"]").should("have.text", "1")
    cy.get("[data-testId=\"dislike-question-button\"]").click()
    cy.get("[data-testId=\"dislike-question-count\"]").should("have.text", "0")
    cy.get("[data-testId=\"mark-question-button\"]").click()
    cy.get("[data-testId=\"mark-question-count\"]").should("have.text", "1")
    cy.get("[data-testId=\"mark-question-button\"]").click()
    cy.get("[data-testId=\"mark-question-count\"]").should("have.text", "0")
    cy.get("[data-testId=\"delete-question-button\"]").click()
    cy.url().should("eq", "http://localhost:3000/")
    cy.get("[data-testid=\"logout\"]").click()
    cy.url().should("include", "/login")
  })
})