describe("登录测试", () => {
  it('测试未登录时的跳转', () => {
    cy.visit('http://localhost:3000')
    cy.url().should("include", "/login")
  })
  it('测试用户名密码错误时无法正常登录', () => {
    cy.visit('http://localhost:3000/login')
    cy.get("[placeholder=\"用户名\"]").type("user1")
    cy.get("[placeholder=\"密码\"]").type("2")
    cy.get("[data-testid=\"login-button\"]").click()
    cy.url().should("include", "/login")
  })
  it('测试用户名密码正确时正常登录及登出', () => {
    cy.visit('http://localhost:3000/login')
    cy.get("[placeholder=\"用户名\"]").type("user1")
    cy.get("[placeholder=\"密码\"]").type("1")
    cy.get("[data-testid=\"login-button\"]").click()
    cy.url().should("eq", "http://localhost:3000/")
    cy.get("[data-testid=\"logout\"]").click()
    cy.url().should("include", "/login")
  })
})

describe("注册测试", () => {
  beforeEach("打开注册界面", () => {
    cy.visit('http://localhost:3000/login')
    cy.get("[data-testid=\"register-show-button\"]").click()
  })
  it('测试在输入为空时注册失败', () => {
    cy.get("[data-testid=\"register-submit-button\"]").click()
    cy.contains("信息不能为空").should("be.visible")
  })
  it('测试在两次输入密码不相同时注册失败', () => {
    cy.get("[placeholder=\"用户名\"]").type("userTest")
    cy.get("[placeholder=\"密码\"]").type("2")
    cy.get("[placeholder=\"重复密码\"]").type("3")
    cy.get("[placeholder=\"邮箱\"]").type("illyaks0@sjtu.edu.cn")
    cy.get("[data-testid=\"register-submit-button\"]").click()
    cy.contains("两次输入密码不相同").should("be.visible")
  })
  it('测试在输入邮箱格式不正确时注册失败', () => {
    cy.get("[placeholder=\"用户名\"]").type("userTest")
    cy.get("[placeholder=\"密码\"]").type("2")
    cy.get("[placeholder=\"重复密码\"]").type("2")
    cy.get("[placeholder=\"邮箱\"]").type("1")
    cy.get("[data-testid=\"register-submit-button\"]").click()
    cy.contains("邮箱格式不正确").should("be.visible")
  })
  it('测试在用户名已被占用时注册失败', () => {
    cy.get("[placeholder=\"用户名\"]").type("user1")
    cy.get("[placeholder=\"密码\"]").type("2")
    cy.get("[placeholder=\"重复密码\"]").type("2")
    cy.get("[placeholder=\"邮箱\"]").type("illyaks0@sjtu.edu.cn")
    cy.get("[data-testid=\"register-submit-button\"]").click()
    cy.contains("用户名已被占用").should("be.visible")
  })
  it('测试成功注册', () => {
    cy.get("[placeholder=\"用户名\"]").type("userTest")
    cy.get("[placeholder=\"密码\"]").type("2")
    cy.get("[placeholder=\"重复密码\"]").type("2")
    cy.get("[placeholder=\"邮箱\"]").type("illyaks0@sjtu.edu.cn")
    cy.get("[data-testid=\"register-submit-button\"]").click()
    cy.contains("注册成功").should("be.visible")
    cy.get("[placeholder=\"用户名\"]").type("userTest")
    cy.get("[placeholder=\"密码\"]").type("2")
    cy.get("[data-testid=\"login-button\"]").click()
    cy.url().should("eq", "http://localhost:3000/")
    cy.get("[data-testid=\"logout\"]").click()
    cy.url().should("include", "/login")
  })
})