describe("提问测试", () => {
  beforeEach("登录到主界面", () => {
    cy.visit('http://localhost:3000/login')
    cy.get("[placeholder=\"用户名\"]").type("user1")
    cy.get("[placeholder=\"密码\"]").type("1")
    cy.get("[data-testid=\"login-button\"]").click()
    cy.url().should("eq", "http://localhost:3000/")
  })
  afterEach("登出系统", () => {
    cy.visit('http://localhost:3000/')
    cy.get("[data-testid=\"logout\"]").click()
    cy.url().should("include", "/login")
  })
  it("测试问题展示", () => {
    cy.contains("如何学习ICS").should("be.visible")
    cy.contains("如何学习ICS").click()
    cy.url().should("include", "qid=1")
    cy.contains("如何学习ICS").should("be.visible")
    cy.get("[data-testid=\"question-tag\"]").first().should("have.text", "校园生活")
  })
  it("测试标题含有敏感词时无法提问", () => {
    cy.contains("去提问！").click()
    cy.get("[placeholder=\"问题标题\"]").should("be.visible")
    cy.get("[placeholder=\"问题标题\"]").type("如何评价18大人员变动")
    cy.get("[placeholder=\"问题内容\"]").type("rt，如何评价18大的人员变动")
    cy.contains("OK").click()
    cy.contains("提问内容不合法").should("be.visible")
  })
  it("测试内容含有敏感词时无法提问", () => {
    cy.contains("去提问！").click()
    cy.get("[placeholder=\"问题标题\"]").should("be.visible")
    cy.get("[placeholder=\"问题标题\"]").type("如何评价会议的人员变动")
    cy.get("[placeholder=\"问题内容\"]").type("rt，如何评价18大的人员变动")
    cy.contains("OK").click()
    cy.contains("提问内容不合法").should("be.visible")
  })
  it("测试正常提问", () => {
    cy.contains("去提问！").click()
    cy.get("[placeholder=\"问题标题\"]").should("be.visible")
    cy.get("[placeholder=\"问题标题\"]").type("如何评价软件工程这个专业")
    cy.get("[placeholder=\"问题内容\"]").type("rt，如何评价软件工程，就业前景如何，学习难度如何")
    cy.contains("校园生活").click()
    cy.contains("OK").click()
    cy.url().should("include", "/ques")
    cy.contains("校园生活").should("be.visible")

  })
})

describe("回答测试", () => {
  beforeEach("登录并打开一个问题", () => {
    cy.visit('http://localhost:3000/login')
    cy.get("[placeholder=\"用户名\"]").type("user1")
    cy.get("[placeholder=\"密码\"]").type("1")
    cy.get("[data-testid=\"login-button\"]").click()
    cy.url().should("eq", "http://localhost:3000/")
    cy.contains("如何学习ICS").should("be.visible")
    cy.contains("如何学习ICS").click()
    cy.url().should("include", "qid=1")
    cy.contains("如何学习ICS").should("be.visible")
  })
  afterEach("登出系统", () => {
    cy.visit('http://localhost:3000/')
    cy.get("[data-testid=\"logout\"]").click()
    cy.url().should("include", "/login")
  })
  it("测试不合法回答", () => {
    cy.contains("回答问题").click()
    cy.get("[class=\"paragraph\"]").clear()
    cy.get("[class=\"paragraph\"]").type("你说得对，但是我不好评价18大的人员变动")
    cy.get("[data-testId=\"question-detail-content\"]").scrollTo("top")
    cy.get("[data-testId=\"answer-submit\"]").click()
    cy.contains("回答内容不合法").should("be.visible")
  })
  it("测试合法回答", () => {
    cy.contains("回答问题").click()
    cy.get("[class=\"paragraph\"]").clear()
    cy.get("[class=\"paragraph\"]").type("测试回答")
    cy.get("[data-testId=\"question-detail-content\"]").scrollTo("top")
    cy.get("[data-testId=\"answer-submit\"]").click()
    cy.get("[data-testId=\"question-detail-content\"]").scrollTo("bottom")
    cy.contains("测试回答").should("be.visible")
  })
})